In [174]:
from __future__ import print_function
import datetime
__author__='__fbb__'

def printContent(timeNow):
    """Creates string to be printed
    Arguments:
    current time as a datetime object
    """

    today5PM = datetime.datetime.now().replace(hour=17, minute=0, second=0, microsecond=0)
    if timeNow < today5PM:
        return "Hello World"
       
    return "GoodNight World"

if __name__ == '__main__':
    print(printContent(datetime.datetime.now()))

Hello World


In [4]:
print ("helloWord")

helloWord


In [5]:
intVariable =3
type(intVariable)

int

In [8]:
if 0:
    print("string")

In [11]:
if (type(intVariable) == int) + (type(intVariable)== float):
    print("yes")  # + = OR,  * = AND

yes


In [13]:
if 0:
    print(0)
else:
    print(1)  #0=false, 1= true

1


In [15]:
import numpy as np

In [26]:
type(np.int16(3))   #takes the 16 byte number and not greater than that.

numpy.int16

In [28]:
a = np.int16(32777)
a

-32759

In [30]:
a = np.int32(32778).dtype    #takes the 32 byte number and not greater than that. 

dtype('int32')

In [31]:
dir(np.int16(3))

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_interface__',
 '__array_priority__',
 '__array_struct__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__index__',
 '__init__',
 '__int__',
 '__invert__',
 '__le__',
 '__lshift__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rlshift__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rrshift__',
 '__rshift__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__xor__',
 'all',
 'any',
 'argmax',
 'argmin',
 'argsort',

In [32]:
stringVariable = "hello"
stringVariable[0]

'h'

In [33]:
myList = ["hello", 1, 2, 4, [4,5,6],5,6]
myList[4][1]

5

In [45]:
myArray = np.array([[1,2.],[3,4.1]])
myArray.dtype

dtype('float64')

In [43]:
myotherArray= np.array(myList[1:])
myotherArray

ValueError: setting an array element with a sequence.

In [46]:
myArray

array([[ 1. ,  2. ],
       [ 3. ,  4.1]])

In [48]:
myArray *2

array([[ 2. ,  4. ],
       [ 6. ,  8.2]])

In [50]:
print (myArray[0] + myArray[1])

[ 1.  2.]


In [56]:
myArray.reshape((1,4), order ='F')  #refer to the order of indexing

array([[ 1. ,  2. ,  3. ,  4.1]])

In [67]:
myThirdArray = np.array([1,2,3,4,5,6,7,8,9,10])
myThirdArray > 2

array([False, False,  True,  True,  True,  True,  True,  True,  True,  True], dtype=bool)

In [78]:
print(myThirdArray[1:-2])
print(myThirdArray[1:11:2])

print(myThirdArray % 2)
sorted(myThirdArray, reverse=True)

[2 3 4 5 6 7 8]
[ 2  4  6  8 10]


[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

#create a numpy array containing numbers from 1 to 10
#then extract only even numbers with boolean operation
#reverse

In [82]:
newArray = np.array(range(1,11))

In [101]:
a = newArray[(newArray%2) == 0][-1::-1]
newArray%2 ==0

array([False,  True, False,  True, False,  True, False,  True, False,  True], dtype=bool)

In [100]:
a+1

array([11,  9,  7,  5,  3])

In [110]:
def extractValues(dataarr):  #once you return you are out of the function no further commands get executed
    if type(dataarr) == np.ndarray:
        return dataarr[-1::-1]
    return -1

In [113]:
extractValues(np.arange(0,10,2))

array([8, 6, 4, 2, 0])

In [115]:
extractValues(1)

-1

#create a function that takes a string
#check if it's a palindrome
returns 1 if true
returns -1 if false
#and also prints yes it's a palindrome
or this is not a palindrome

In [155]:
def checkPal(string):
    if (string.lower()[::] == string.lower()[::-1]):
        halfpal= string[:int(float(len(string))/2.0+0.5)]
        
        print("this is a palindrome",halfpal )
        return 1
    else:
        print("this is not a palindrome")
        return -1

In [156]:
checkPal("HannaH")

this is a palindrome Han


1

In [161]:
"the fox ate the cat".split()

['the', 'fox', 'ate', 'the', 'cat']

In [165]:
"the fox ate the cat  ".strip('t').split()

['he', 'fox', 'ate', 'the', 'cat']

In [166]:
' '.join("the fox ate the cat".strip().split(' ')).replace('rabbit','mouse')

'the fox ate the cat'

In [179]:
fout = open("temp.txt", 'w')

for i in  range(10):
    for j in  range(10):
        print(j,"", end = "", file= fout)
    print ("",file= fout)


In [172]:
temList=[]

fin = open('temp.txt', 'r')
for ln in fin.readlines():
    for dig in ln.split():
        temList.append(int(dig))


In [180]:
!curl -O https://github.com/fedhere/PyBOOT/blob/master/busBusses.npy

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 32030    0 32030    0     0   143k      0 --:--:-- --:--:-- --:--:--  143k
